name: Release to NuGet

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.ref_name }}    
    
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore src/DocuWare.Platform.ServerClient.Abstracts/DocuWare.Platform.ServerClient.Abstracts.csproj

    - name: Build
      run: dotnet build src/DocuWare.Platform.ServerClient.Abstracts/DocuWare.Platform.ServerClient.Abstracts.csproj --no-restore -c Release -p:Version=$VERSION

    # - name: Test
    #   run: dotnet test -c Release --no-build

    - name: Pack (NuGet + Symbols)
      run: |
        mkdir -p artifacts
        dotnet pack src/DocuWare.Platform.ServerClient.Abstracts/DocuWare.Platform.ServerClient.Abstracts.csproj \
          -c Release \
          --no-build \
          -p:Version=$VERSION \
          -p:IncludeSymbols=true \
          -p:SymbolPackageFormat=snupkg \
          --output ./artifacts

    # Sign once a certificate is available
    # - name: Code signing
    #   run: dotnet build -c Release -p:SignAssembly=true -p:AssemblyOriginatorKey=key.snk

    - name: Push NuGet package
      run: |
        dotnet nuget push "artifacts/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
    - name: Push Symbols
      run: |
        dotnet nuget push "artifacts/*.snupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
